Importamos librerias

In [628]:
import pandas as pd

Cargamos los data frames

In [629]:
# Carga CSV
bank_df = pd.read_csv('../datos/bank-additional.csv', sep=',')

In [630]:
# Carga Excel con varias hojas
customer_df_2012 = pd.read_excel('../datos/customer-details.xlsx', sheet_name='2012')
customer_df_2013 = pd.read_excel('../datos/customer-details.xlsx', sheet_name='2013')
customer_df_2014 = pd.read_excel('../datos/customer-details.xlsx', sheet_name='2014')

Exploramos el primer Dataframe

In [631]:
bank_df.sample(15)

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
26875,27019,50.0,management,DIVORCED,university.degree,0.0,1.0,0.0,cellular,21,...,-0.1,"93,2",-42,"4,021","5195,8",no,22-mayo-2016,41.901,-123.845,8fcf1918-e4b5-4e99-b195-562186ce7965
16809,16906,NaN,services,DIVORCED,high.school,0.0,0.0,0.0,cellular,539,...,1.4,"93,918","-42,7","4,962","5228,1",no,12-agosto-2015,48.103,-116.098,402d316e-a3dc-46a1-bf0f-cf7c81ec30a4
29343,29487,46.0,entrepreneur,MARRIED,NaN,0.0,1.0,0.0,cellular,466,...,-1.8,"93,075","-47,1","1,405","5099,1",no,16-marzo-2018,37.485,-75.753,09d9c66e-7ee0-495a-a207-36c1dab74c18
20489,20586,47.0,admin.,DIVORCED,high.school,0.0,0.0,0.0,cellular,204,...,1.4,"93,444","-36,1",NaN,"5228,1",no,26-abril-2017,37.635,-69.002,6f8712c1-6635-42d6-9883-fba9f05da123
4064,4161,47.0,technician,MARRIED,professional.course,NaN,1.0,0.0,telephone,197,...,1.1,"93,994","-36,4",NaN,5191,no,13-agosto-2018,29.212,-74.818,79e0697b-645f-4295-8282-37120bf4a67d
225,241,36.0,technician,SINGLE,professional.course,0.0,0.0,0.0,telephone,124,...,1.1,"93,994","-36,4",NaN,5191,no,31-octubre-2016,30.137,-100.452,284358a1-8bcd-4b29-babb-940b979dd941
5172,5269,40.0,blue-collar,MARRIED,basic.9y,0.0,1.0,0.0,telephone,811,...,1.1,NaN,"-36,4","4,857",5191,no,10-marzo-2017,43.780,-93.728,b9a80260-d9b7-418b-8710-6b0a772c5500
26014,26136,29.0,services,SINGLE,high.school,0.0,1.0,0.0,cellular,146,...,-0.1,"93,2",-42,"4,12","5195,8",no,9-febrero-2016,47.551,-90.894,65d5f1ba-5648-45cb-b54e-4619b61b133e
42769,7271,40.0,technician,MARRIED,basic.9y,NaN,0.0,1.0,telephone,171,...,1.1,"93,994","-36,4",NaN,5191,no,7-julio-2018,46.340,-83.007,83d861a4-e3b5-4ad9-8aed-d313f86edd08
21034,21131,49.0,admin.,MARRIED,basic.9y,0.0,1.0,0.0,cellular,161,...,1.4,"93,444","-36,1","4,963","5228,1",no,4-febrero-2017,34.958,-102.203,82024614-a6c8-43c4-b933-432f70e3d7e7
31024,31168,31.0,blue-collar,MARRIED,basic.6y,NaN,0.0,0.0,cellular,188,...,-1.8,"92,893","-46,2","1,334","5099,1",no,11-octubre-2019,49.182,-77.503,baf988a4-844b-4237-bcb4-b0bc482b6999
1496,1593,31.0,admin.,MARRIED,university.degree,0.0,1.0,0.0,telephone,218,...,1.1,"93,994","-36,4","4,855",5191,no,25-enero-2018,31.350,-82.817,c3e8ba72-bfdc-4b59-8ed0-6bf35c400723
1482,1579,32.0,blue-collar,MARRIED,basic.9y,NaN,0.0,0.0,telephone,180,...,1.1,"93,994","-36,4","4,855",5191,no,19-septiembre-2019,45.319,-115.023,486373ec-a0c4-4ae7-8ffd-2152f4a23a70
20890,20987,NaN,technician,MARRIED,high.school,NaN,0.0,0.0,cellular,206,...,1.4,"93,444","-36,1","4,964","5228,1",no,3-diciembre-2015,31.454,-69.746,6fc34228-1194-4597-b471-af5a80c04569
29426,29570,42.0,blue-collar,MARRIED,basic.4y,0.0,1.0,0.0,cellular,257,...,-1.8,"93,075","-47,1",NaN,"5099,1",no,30-junio-2016,45.668,-109.180,4871b22a-4534-4726-8f8b-178b32f0dd33

In [632]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  object
 3   marital         42915 non-null  object
 4   education       41193 non-null  object
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  object
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  object
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  object
 16  cons.conf.idx   43000 non-null  object
 17  euribor3m       33744 non-null  object
 18  nr.employed     43000 non-null  object
 19  y               43000 non-null  object
 20  date            42752 non-null  object
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  object
dtypes: float64(7), int64(5), object(12)
memory usage: 7.9+ MB

In [633]:
bank_df.describe()

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.000000,37880.000000,34019.000000,41974.000000,41974.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000,43000.000000
mean,20651.099047,39.977112,0.000088,0.535998,0.155620,257.739279,2.567233,962.330953,0.174023,0.077128,36.856697,-95.939067
std,11868.770913,10.437957,0.009390,0.498708,0.362499,258.666033,2.772294,187.260394,0.497366,1.573898,7.225948,16.752282
min,0.000000,17.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,-3.400000,24.396000,-124.997000
25%,10381.750000,32.000000,0.000000,0.000000,0.000000,102.000000,1.000000,999.000000,0.000000,-1.800000,30.614750,-110.494250
50%,20642.500000,38.000000,0.000000,1.000000,0.000000,179.000000,2.000000,999.000000,0.000000,1.100000,36.761000,-95.899500
75%,30930.250000,47.000000,0.000000,1.000000,0.000000,319.000000,3.000000,999.000000,0.000000,1.400000,43.113250,-81.427750
max,41187.000000,98.000000,1.000000,1.000000,1.000000,4918.000000,56.000000,999.000000,7.000000,1.400000,49.384000,-66.937000

In [634]:
print(bank_df.dtypes.value_counts())

object     12
float64     7
int64       5
Name: count, dtype: int64

In [635]:
bank_df.describe().round(2)

,Unnamed: 0,age,default,housing,loan,duration,campaign,pdays,previous,emp.var.rate,latitude,longitude
count,43000.00,37880.00,34019.00,41974.00,41974.00,43000.00,43000.00,43000.00,43000.00,43000.00,43000.00,43000.00
mean,20651.10,39.98,0.00,0.54,0.16,257.74,2.57,962.33,0.17,0.08,36.86,-95.94
std,11868.77,10.44,0.01,0.50,0.36,258.67,2.77,187.26,0.50,1.57,7.23,16.75
min,0.00,17.00,0.00,0.00,0.00,0.00,1.00,0.00,0.00,-3.40,24.40,-125.00
25%,10381.75,32.00,0.00,0.00,0.00,102.00,1.00,999.00,0.00,-1.80,30.61,-110.49
50%,20642.50,38.00,0.00,1.00,0.00,179.00,2.00,999.00,0.00,1.10,36.76,-95.90
75%,30930.25,47.00,0.00,1.00,0.00,319.00,3.00,999.00,0.00,1.40,43.11,-81.43
max,41187.00,98.00,1.00,1.00,1.00,4918.00,56.00,999.00,7.00,1.40,49.38,-66.94

In [636]:
# Ver cantidad de valores faltantes por columna
missing_values_bank = bank_df.isnull().sum()

# Mostrar solo columnas que tienen al menos un valor nulo
missing_values_bank = missing_values_bank[missing_values_bank > 0]

print("Valores faltantes por columna:")
print(missing_values_bank)

Valores faltantes por columna:
age               5120
job                345
marital             85
education         1807
default           8981
housing           1026
loan              1026
cons.price.idx     471
euribor3m         9256
date               248
dtype: int64

In [637]:
porcentaje_nulos_bank = bank_df.isnull().mean().round(4) * 100
print(porcentaje_nulos_bank)

Unnamed: 0         0.00
age               11.91
job                0.80
marital            0.20
education          4.20
default           20.89
housing            2.39
loan               2.39
contact            0.00
duration           0.00
campaign           0.00
pdays              0.00
previous           0.00
poutcome           0.00
emp.var.rate       0.00
cons.price.idx     1.10
cons.conf.idx      0.00
euribor3m         21.53
nr.employed        0.00
y                  0.00
date               0.58
latitude           0.00
longitude          0.00
id_                0.00
dtype: float64

Comprobamos la correspondencia de un identificardor unico entre los dos data frame par combinarlos posteriormente

In [638]:
df_customer_combinados['ID'].isin(bank_df['id_']).all()
df_customer_combinados['ID'].isin(bank_df['id_']).value_counts()

ID
True     43000
False      170
Name: count, dtype: int64

Quitamos la primera columna de "bank_df"

In [639]:
# Drop the first column by index
bank_df = bank_df.drop(bank_df.columns[0], axis=1)

Cambiamos el tipo valores a boleano por las columnas siguientes: 
'default', 'housing' y 'loan'

In [640]:
# comprobamos si el dato es 0-1 boleano o numerico indicando una cantidad con la finalidad de transformar la columna
# Valores únicos en la columna 'housing'
print("Valores únicos en 'housing':", bank_df['housing'].unique())

# Valores únicos en la columna 'loan'
print("Valores únicos en 'loan':", bank_df['loan'].unique())

Valores únicos en 'housing': [ 0.  1. nan]
Valores únicos en 'loan': [ 0.  1. nan]

In [641]:
# convertir las columnas 'default', 'housing' y 'loan' a tipo booleano
bank_df[['default', 'housing', 'loan']] = bank_df[['default', 'housing', 'loan']].astype(bool)
# Verificamos los tipos de datos después de la conversión
print(bank_df.dtypes[['default', 'housing', 'loan']])

default    bool
housing    bool
loan       bool
dtype: object

Remplazamos valores nulos de la columna "age" por un promedio correspondiente al perfil del cliente segun criterio de empleo y educacion.

In [642]:
# Agrupar por 'job' y 'education' y calcular la media de 'age'
tabla_promedios = bank_df.groupby(['job', 'education'])['age'].mean().round(0).reset_index()

# Mostrar la tabla resultante
print(tabla_promedios)

           job            education   age
0       admin.             basic.4y  50.0
1       admin.             basic.6y  43.0
2       admin.             basic.9y  41.0
3       admin.          high.school  38.0
4       admin.           illiterate   NaN
..         ...                  ...   ...
67  unemployed             basic.6y  41.0
68  unemployed             basic.9y  42.0
69  unemployed          high.school  38.0
70  unemployed  professional.course  41.0
71  unemployed    university.degree  37.0

[72 rows x 3 columns]

In [643]:
# gestion de nulos de la columna age
# paso 1: Agrupamos por 'job' y 'education' y rellenamos los valores nulos en 'age' con la media del grupo
bank_df['age'] = bank_df.groupby(['job', 'education'])['age'].transform(lambda x: x.fillna(round(x.mean(), 0)))
# Paso 2: Imputar los que siguen siendo NaN (grupos sin edad registrada) con la media global
bank_df['age'] = bank_df['age'].fillna(round(bank_df['age'].mean(), 0))

In [644]:
bank_df['age'].isnull().sum()  # Verificamos que no queden nulos en 'age'

np.int64(0)

Cambiamos el tipo valores a entero por la columnas 'age'':

In [645]:
#convertimos la columna age de formato float a int
bank_df['age'] = bank_df['age'].astype(int)

In [646]:
bank_df.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
27590,24,student,SINGLE,basic.9y,False,True,False,cellular,96,2,...,-1.8,"92,843",-50,"1,799","5099,1",yes,16-enero-2015,41.192,-104.580,8f6cad11-49b9-48a7-92a3-f8b36915e9d6
40607,38,services,SINGLE,high.school,False,True,False,cellular,336,2,...,-1.1,"94,199","-37,5","0,879","4963,6",yes,15-enero-2019,48.002,-118.769,30ca0f28-5426-4b81-8f5f-092437d47b01
11222,60,management,MARRIED,university.degree,False,True,False,telephone,89,2,...,1.4,"94,465","-41,8","4,961","5228,1",no,22-septiembre-2019,46.886,-83.031,6e628c06-5549-49d2-8aab-859b9750382a
9683,47,services,MARRIED,basic.6y,False,False,False,telephone,107,3,...,1.4,"94,465","-41,8","4,959","5228,1",no,29-septiembre-2015,30.018,-92.722,7b9de182-adce-418e-8199-5900f294590c
27514,50,admin.,DIVORCED,university.degree,False,True,False,cellular,72,3,...,-0.1,"93,2",-42,"4,021","5195,8",no,10-diciembre-2017,35.064,-91.728,223c6b7d-c35d-465a-b91a-318bcebed487
7345,36,housemaid,MARRIED,high.school,False,True,True,telephone,135,3,...,1.1,"93,994","-36,4","4,864",5191,no,21-julio-2015,43.670,-89.979,972f0a19-0aad-4148-89ec-4c1d675baf66
18156,26,blue-collar,MARRIED,high.school,False,False,False,cellular,142,3,...,1.4,"93,918","-42,7","4,963","5228,1",no,21-junio-2018,48.464,-95.482,574b6797-b047-4087-adf5-e6fc5e563103
10629,43,admin.,MARRIED,university.degree,False,True,False,telephone,411,6,...,1.4,"94,465","-41,8","4,961","5228,1",no,10-julio-2016,35.431,-95.871,76e3361b-c717-4850-8ef0-bea50fdcb9bd
6729,40,blue-collar,SINGLE,NaN,True,False,False,telephone,299,3,...,1.1,"93,994","-36,4","4,857",5191,no,21-diciembre-2018,32.181,-123.213,b14634b0-5d1c-4224-a1e7-865233705075
12836,26,entrepreneur,MARRIED,basic.4y,True,False,False,cellular,510,1,...,1.4,"93,918","-42,7","4,962","5228,1",no,25-marzo-2019,39.590,-105.612,3eba8da0-9661-4f20-ae4b-54171a0f7cfc
29655,39,admin.,SINGLE,university.degree,False,True,False,cellular,72,1,...,-1.8,"93,075","-47,1","1,405","5099,1",no,4-junio-2018,25.742,-75.524,2221d2c0-e9c9-4c25-9551-245b524f7aad
20045,39,admin.,SINGLE,university.degree,True,False,True,cellular,155,1,...,1.4,"93,444","-36,1",NaN,"5228,1",no,10-septiembre-2016,27.875,-119.493,c9846c93-7d51-43af-805b-d22811acc9b2
30467,45,admin.,MARRIED,university.degree,False,True,False,cellular,254,4,...,-1.8,"92,893","-46,2","1,354","5099,1",no,25-mayo-2017,27.390,-88.741,e11983a1-c61a-49f0-b217-c3c00f591e1e
39329,59,retired,DIVORCED,high.school,False,True,False,cellular,247,2,...,-1.8,"93,749","-34,6","0,644","5008,7",no,15-mayo-2017,47.170,-115.089,af639c52-00df-4842-8e2d-1a593a175f40
28054,36,blue-collar,MARRIED,basic.9y,False,True,False,cellular,226,1,...,-1.8,"93,075","-47,1","1,453","5099,1",no,2-marzo-2016,34.686,-120.866,f362f694-0057-44fa-bc0f-63804550ddf8

Eliminacion de lineas sin valores de los atributos 'job', 'marital' y 'date' que representan menos de 2,4% del data frame

In [647]:

bank_df = bank_df.dropna(subset=['job', 'marital', 'housing', 'loan','date'])

Añadimos el valor "unknown" en la columna "education" por todos las valores faltantes

In [648]:
bank_df['education'] = bank_df['education'].fillna('unknown')

Comprobamos el avance en gestion de nulos

In [649]:
porcentaje_nulos_bank = bank_df.isnull().mean().round(4) * 100
print(porcentaje_nulos_bank)

age                0.00
job                0.00
marital            0.00
education          0.00
default            0.00
housing            0.00
loan               0.00
contact            0.00
duration           0.00
campaign           0.00
pdays              0.00
previous           0.00
poutcome           0.00
emp.var.rate       0.00
cons.price.idx     1.09
cons.conf.idx      0.00
euribor3m         21.53
nr.employed        0.00
y                  0.00
date               0.00
latitude           0.00
longitude          0.00
id_                0.00
dtype: float64

En la columna "pdays" el valor 999 esta presente por cada cuando el cliente nunca fue contactado y el calculo desde la ultima llamada no se puede hacer. Cambiaremos este valor por NaN para poder excluirlo de calculo posteriores (promedio ect..)

In [650]:
bank_df.loc[bank_df['pdays'] == 999, 'pdays'] = pd.NA

Seguimos con la transformacion de datos con objeto a float por las columnas siguientes:  
'cons.price.idx', 'cons.conf.idx' y 'euribor3m'  
Cambiamos todas las comas por un punto para evitar errores

In [651]:
# Lista de columnas a transformar
columns_to_convert = ['cons.price.idx', 'cons.conf.idx', 'euribor3m']

# Reemplazar comas por puntos y convertir a float
for col in columns_to_convert:
    bank_df[col] = bank_df[col].astype(str).str.replace(',', '.')
    bank_df[col] = bank_df[col].astype(float)

In [652]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42332 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             42332 non-null  int64
 1   job             42332 non-null  object
 2   marital         42332 non-null  object
 3   education       42332 non-null  object
 4   default         42332 non-null  bool
 5   housing         42332 non-null  bool
 6   loan            42332 non-null  bool
 7   contact         42332 non-null  object
 8   duration        42332 non-null  int64
 9   campaign        42332 non-null  int64
 10  pdays           1551 non-null   float64
 11  previous        42332 non-null  int64
 12  poutcome        42332 non-null  object
 13  emp.var.rate    42332 non-null  float64
 14  cons.price.idx  41872 non-null  float64
 15  cons.conf.idx   42332 non-null  float64
 16  euribor3m       33218 non-null  float64
 17  nr.employed     42332 non-null  object
 18  y               42332 non-null  object
 19  date            42332 non-null  object
 20  latitude        42332 non-null  float64
 21  longitude       42332 non-null  float64
 22  id_             42332 non-null  object
dtypes: bool(3), float64(7), int64(4), object(9)
memory usage: 6.9+ MB

Se observa una relacione entre las columnas "cons.price.idx" y "cons.conf.idx", parece que los valores se corresponden.
vamos a confirmar la hipotesis y si se confirma rellenaremos los valores faltantes

In [653]:
# Agrupar por 'cons.conf.idx' y contar los valores únicos de 'cons.price.idx'
unique_mapping = bank_df.groupby('cons.conf.idx')['cons.price.idx'].nunique()

# Verificar si todos los valores únicos son 1
is_unique_mapping = (unique_mapping == 1).all()

# Mostrar el resultado
if is_unique_mapping:
    print("Cada valor único en 'cons.conf.idx' tiene un único valor correspondiente en 'cons.price.idx'.")
else:
    print("Hay valores en 'cons.conf.idx' que tienen más de un valor correspondiente en 'cons.price.idx'.")

Cada valor único en 'cons.conf.idx' tiene un único valor correspondiente en 'cons.price.idx'.

In [654]:
# Crear un diccionario de mapeo desde 'cons.conf.idx' a 'cons.price.idx'
mapping = bank_df.dropna(subset=['cons.price.idx']).drop_duplicates(subset=['cons.conf.idx'])\
    .set_index('cons.conf.idx')['cons.price.idx'].to_dict()

# Rellenar los valores faltantes en 'cons.price.idx' usando el mapeo
bank_df['cons.price.idx'] = bank_df.apply(
    lambda row: mapping[row['cons.conf.idx']] if pd.isna(row['cons.price.idx']) else row['cons.price.idx'],
    axis=1)

In [655]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42332 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             42332 non-null  int64
 1   job             42332 non-null  object
 2   marital         42332 non-null  object
 3   education       42332 non-null  object
 4   default         42332 non-null  bool
 5   housing         42332 non-null  bool
 6   loan            42332 non-null  bool
 7   contact         42332 non-null  object
 8   duration        42332 non-null  int64
 9   campaign        42332 non-null  int64
 10  pdays           1551 non-null   float64
 11  previous        42332 non-null  int64
 12  poutcome        42332 non-null  object
 13  emp.var.rate    42332 non-null  float64
 14  cons.price.idx  42332 non-null  float64
 15  cons.conf.idx   42332 non-null  float64
 16  euribor3m       33218 non-null  float64
 17  nr.employed     42332 non-null  object
 18  y               42332 non-null  object
 19  date            42332 non-null  object
 20  latitude        42332 non-null  float64
 21  longitude       42332 non-null  float64
 22  id_             42332 non-null  object
dtypes: bool(3), float64(7), int64(4), object(9)
memory usage: 6.9+ MB

In [656]:
print(porcentaje_nulos_bank)

age                0.00
job                0.00
marital            0.00
education          0.00
default            0.00
housing            0.00
loan               0.00
contact            0.00
duration           0.00
campaign           0.00
pdays              0.00
previous           0.00
poutcome           0.00
emp.var.rate       0.00
cons.price.idx     1.09
cons.conf.idx      0.00
euribor3m         21.53
nr.employed        0.00
y                  0.00
date               0.00
latitude           0.00
longitude          0.00
id_                0.00
dtype: float64

In [657]:
bank_df.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
10777,47,services,MARRIED,high.school,True,False,False,telephone,311,1,...,1.4,94.465,-41.8,4.962,"5228,1",no,11-septiembre-2019,47.870,-115.482,b261b952-6618-46f9-bcf9-578c0554d524
13194,32,admin.,DIVORCED,high.school,False,False,False,cellular,89,3,...,1.4,93.918,-42.7,4.962,"5228,1",no,13-diciembre-2015,33.745,-119.934,0747d734-39c4-4b1d-934c-3516cb5f933e
26619,53,self-employed,DIVORCED,university.degree,False,False,False,cellular,380,1,...,-0.1,93.200,-42.0,4.076,"5195,8",no,26-febrero-2019,34.786,-108.942,6b31cf3b-03e6-4d8f-8091-345dc7333af4
24091,55,blue-collar,MARRIED,basic.9y,False,False,False,cellular,1303,1,...,-0.1,93.200,-42.0,4.191,"5195,8",yes,5-mayo-2015,28.761,-69.539,fc0ecf5f-8ed3-4b90-9240-4ac5fcb56e7a
23553,32,technician,SINGLE,university.degree,False,False,False,cellular,83,3,...,1.4,93.444,-36.1,NaN,"5228,1",no,18-febrero-2015,47.794,-122.610,02e68373-e34c-443e-bbd8-00bac47af685
34702,37,admin.,SINGLE,high.school,False,True,False,telephone,26,6,...,-1.8,92.893,-46.2,NaN,"5099,1",no,18-diciembre-2015,31.285,-68.254,34bc8534-acd9-4007-954f-9fd76aee9169
40245,60,housemaid,MARRIED,basic.4y,False,False,False,cellular,270,4,...,-1.7,94.027,-38.3,0.905,"4991,6",no,20-abril-2018,33.942,-101.769,9947610f-f1c8-4df6-8df7-52e04165dc0d
10136,41,admin.,MARRIED,basic.9y,False,False,False,telephone,270,15,...,1.4,94.465,-41.8,4.960,"5228,1",no,11-junio-2016,29.092,-97.792,e5aced8c-e010-43a0-a5b3-ab4ca4bd570d
22412,35,technician,SINGLE,university.degree,False,True,False,cellular,65,13,...,1.4,93.444,-36.1,4.964,"5228,1",no,28-febrero-2018,37.262,-87.502,afa025c6-253b-490b-9dd4-5015421b474e
19752,47,entrepreneur,MARRIED,high.school,False,True,True,cellular,86,3,...,1.4,93.444,-36.1,4.966,"5228,1",no,19-diciembre-2018,36.603,-93.631,2b62f374-a048-4b0e-9ad4-ee8147f04e25
24864,41,management,MARRIED,high.school,False,True,False,telephone,159,1,...,-0.1,93.200,-42.0,4.153,"5195,8",no,12-octubre-2018,30.489,-100.699,d8951c80-b948-4258-95bc-6da1c913b59a
3130,33,technician,MARRIED,professional.course,False,False,False,telephone,191,4,...,1.1,93.994,-36.4,NaN,5191,no,28-abril-2016,47.831,-72.060,308fa681-df30-417a-a90c-d51af5dd2c1d
30220,28,student,SINGLE,high.school,False,True,False,cellular,121,1,...,-1.8,93.075,-47.1,NaN,"5099,1",no,24-octubre-2018,44.117,-69.820,19727dd9-228b-4443-bb3e-96f2c6461865
3988,32,blue-collar,MARRIED,basic.9y,False,True,False,telephone,181,1,...,1.1,93.994,-36.4,4.858,5191,no,28-octubre-2019,29.366,-96.902,06f0ad02-b58b-4160-af35-4175ac43f8f6
22804,52,services,MARRIED,professional.course,True,True,True,cellular,84,3,...,1.4,93.444,-36.1,4.965,"5228,1",no,29-diciembre-2015,37.128,-75.110,9b553737-7f87-448b-afa0-5d4681baed62

vamos a cambiar y unificar el formato de la columna "nr.employed"

In [658]:
# Reemplazar comas por puntos antes de convertir a float
bank_df['nr.employed'] = bank_df['nr.employed'].astype(str).str.replace(',', '.')
bank_df['nr.employed'] = bank_df['nr.employed'].astype(float)

In [659]:
# Convertir a texto con 1 decimal, útil para visualización o comparación
bank_df['nr.employed'] = bank_df['nr.employed'].map(lambda x: f"{x:.1f}")
# Verificar el resultado
print(bank_df['nr.employed'].unique())

['5191.0' '5228.1' '5195.8' '5176.3' '5099.1' '5076.2' '5017.5' '5023.5'
 '5008.7' '4991.6' '4963.6']

In [660]:
# quitamos el punto de la columna nr.employed
bank_df['nr.employed'] = bank_df['nr.employed'].str.replace('.', '')
# Verificar el resultado
print(bank_df['nr.employed'].unique())
# Convertir a int
bank_df['nr.employed'] = bank_df['nr.employed'].astype(int)

['51910' '52281' '51958' '51763' '50991' '50762' '50175' '50235' '50087'
 '49916' '49636']

In [661]:
bank_df.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
22998,40,admin.,SINGLE,high.school,False,True,False,cellular,87,1,...,1.4,93.444,-36.1,4.965,52281,no,27-noviembre-2019,49.368,-122.286,aa0d0404-4cb5-477f-a159-0a0ac13f9677
23851,35,technician,MARRIED,high.school,False,True,False,telephone,129,1,...,1.4,93.444,-36.1,4.963,52281,no,13-noviembre-2017,28.430,-70.895,96a33eff-a7d1-4275-ad27-71dfb8974814
13098,51,technician,MARRIED,university.degree,True,True,True,cellular,89,1,...,1.4,93.918,-42.7,4.962,52281,no,8-julio-2017,35.463,-100.608,555e04a0-a51d-4faa-a829-495d8bddd2b8
8974,44,services,MARRIED,high.school,False,True,False,telephone,172,3,...,1.4,94.465,-41.8,4.866,52281,no,2-marzo-2017,48.529,-100.949,ae9f238d-4050-481e-8b69-15a7cfe072cd
4600,39,technician,SINGLE,professional.course,True,False,False,telephone,27,1,...,1.1,93.994,-36.4,4.858,51910,no,20-julio-2018,35.759,-98.013,dc1fa860-7bff-4b6a-b793-39c4ddc23d1e
28136,25,unemployed,SINGLE,professional.course,False,False,False,cellular,268,1,...,-1.8,93.075,-47.1,1.445,50991,no,9-mayo-2015,35.020,-108.214,c986e76e-b654-4375-b045-bb0429de8d39
15187,46,admin.,SINGLE,university.degree,True,True,False,cellular,153,1,...,1.4,93.918,-42.7,4.958,52281,no,2-noviembre-2015,37.063,-106.400,e66a6c64-30bc-42e8-9277-20eb204118bb
6127,59,entrepreneur,MARRIED,university.degree,True,True,False,telephone,217,2,...,1.1,93.994,-36.4,NaN,51910,no,21-diciembre-2019,42.688,-122.998,abe9149f-e4a6-41c4-9843-73634c792db8
40927,19,student,SINGLE,basic.9y,False,True,False,cellular,182,1,...,-1.1,94.767,-50.8,1.048,49636,no,2-diciembre-2019,48.285,-92.319,6268c11b-fbd6-46bd-ae71-1e6346884d1d
19778,39,admin.,MARRIED,professional.course,False,True,False,cellular,348,1,...,1.4,93.444,-36.1,4.966,52281,no,13-mayo-2016,35.573,-122.187,e7b29221-289f-49b4-b4e8-6348a7dde40f
41705,56,services,DIVORCED,high.school,True,False,False,telephone,154,1,...,1.1,93.994,-36.4,4.857,51910,no,18-enero-2018,37.969,-119.862,22753e22-8769-4f57-bb70-23ac6c87a0bd
34476,51,blue-collar,MARRIED,basic.4y,False,True,True,cellular,668,2,...,-1.8,92.893,-46.2,1.266,50991,yes,28-agosto-2017,44.542,-122.077,c8470400-de48-45a6-961c-25154a174ec8
35479,46,management,MARRIED,university.degree,False,False,False,cellular,143,1,...,-1.8,92.893,-46.2,NaN,50991,no,8-mayo-2017,40.613,-117.618,51579d05-2ede-41a8-a295-42d138f7de4d
29003,40,technician,SINGLE,professional.course,False,True,False,cellular,53,1,...,-1.8,93.075,-47.1,NaN,50991,no,16-abril-2015,29.420,-89.236,556d6210-4b12-4151-a58d-4596dc5c04f5
30413,43,blue-collar,MARRIED,basic.4y,False,False,False,cellular,191,3,...,-1.8,92.893,-46.2,1.354,50991,no,3-agosto-2018,24.640,-68.731,725a7314-6d02-4153-987c-d7d5b59c158e

Renombramos la columna "y" como "subscribed", reemplazamos los valores de la columna y el tipo a boleano

In [662]:
bank_df.rename(columns={'y': 'subscribed'}, inplace=True)
# Reemplazar los valores de la columna 'subscribed' y convertir a booleano
bank_df['subscribed'] = bank_df['subscribed'].map({'yes': True, 'no': False})
# Verificar el resultado
bank_df.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,subscribed,date,latitude,longitude,id_
13202,32,technician,SINGLE,university.degree,False,True,False,cellular,89,1,...,1.4,93.918,-42.7,4.962,52281,False,24-agosto-2019,45.393,-105.032,346e810c-a957-4360-9be4-1f108e1cae22
18431,30,technician,SINGLE,university.degree,False,False,False,cellular,131,8,...,1.4,93.918,-42.7,4.968,52281,False,29-mayo-2018,48.393,-79.862,15f6a744-00dc-4664-9d26-843a9862c70b
6960,47,blue-collar,MARRIED,basic.4y,True,False,False,telephone,159,1,...,1.1,93.994,-36.4,4.860,51910,False,12-noviembre-2018,27.834,-90.960,f6128e2b-141d-4268-a16b-4f4a0ec6fcaf
13236,36,blue-collar,SINGLE,high.school,False,False,False,cellular,118,2,...,1.4,93.918,-42.7,4.962,52281,False,21-julio-2018,31.763,-87.554,2419ca8d-97ff-4c25-bf39-42db9c776b62
19035,46,technician,MARRIED,professional.course,False,False,True,cellular,166,2,...,1.4,93.444,-36.1,NaN,52281,False,23-agosto-2015,42.259,-112.952,67ac782c-3375-45ad-8517-8c6f4eccc96f
4268,42,self-employed,MARRIED,high.school,False,False,False,telephone,83,1,...,1.1,93.994,-36.4,NaN,51910,False,21-diciembre-2015,31.485,-113.382,2e722f46-c8c9-4b7a-bf04-a68ddbb5edf7
30407,30,self-employed,MARRIED,university.degree,False,False,False,cellular,107,4,...,-1.8,92.893,-46.2,1.354,50991,False,25-enero-2016,45.505,-100.615,8db6f512-2ab2-4cc5-b7e3-2fa6b0d028d2
38117,28,admin.,SINGLE,high.school,False,False,False,telephone,958,1,...,-3.4,92.431,-26.9,0.742,50175,True,31-julio-2018,25.154,-95.582,e436d949-1e5c-42bb-b7eb-93b56ea6d024
28145,34,services,MARRIED,high.school,False,False,False,cellular,462,2,...,-1.8,93.075,-47.1,1.445,50991,False,7-diciembre-2019,41.806,-115.928,17c88347-334b-4c2b-9590-3210f426c9bd
12510,59,retired,MARRIED,university.degree,True,False,False,telephone,95,2,...,1.4,93.918,-42.7,4.960,52281,False,5-febrero-2019,46.436,-93.043,8746b3d4-24a0-4506-89c3-f9ef87e7c407
2776,38,technician,MARRIED,professional.course,True,True,False,telephone,157,1,...,1.1,93.994,-36.4,4.859,51910,False,20-diciembre-2017,43.607,-81.495,1b4df5a3-bd27-4643-9080-a5d0fe9934b1
34996,42,services,MARRIED,basic.9y,False,True,False,cellular,152,1,...,-1.8,92.893,-46.2,1.250,50991,False,28-enero-2019,29.011,-117.968,2e53eef1-4875-4176-961e-295e3851c8af
21068,35,technician,MARRIED,professional.course,False,True,False,cellular,70,2,...,1.4,93.444,-36.1,4.963,52281,False,2-septiembre-2017,48.874,-92.160,13e7fc8e-7e52-4305-be26-8dd175080187
8,24,technician,SINGLE,professional.course,False,True,False,telephone,380,1,...,1.1,93.994,-36.4,4.857,51910,False,18-enero-2018,44.632,-85.811,87b79988-2be5-419d-88f4-56655852c565
1918,44,admin.,SINGLE,high.school,False,False,False,telephone,111,2,...,1.1,93.994,-36.4,4.857,51910,False,8-julio-2019,41.517,-106.266,d3a65ff7-a982-4663-ac05-b48c8a3e79b3

Cambiamos los valores de la columna "date" a un formato fecha dd/mm/aa

In [663]:
# Diccionario de meses en español
meses_es = {
    'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
    'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
    'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
}

# Reemplazar mes por número en la cadena
bank_df['date'] = bank_df['date'].apply(
    lambda x: x.replace(x.split('-')[1], meses_es[x.split('-')[1]])
)

# Convertir a datetime ahora que el mes es numérico
bank_df['date'] = pd.to_datetime(bank_df['date'], format='%d-%m-%Y')

In [664]:

bank_df['date'] = bank_df['date'].dt.strftime('%d-%m-%Y')

In [665]:
bank_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42332 entries, 0 to 42999
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             42332 non-null  int64
 1   job             42332 non-null  object
 2   marital         42332 non-null  object
 3   education       42332 non-null  object
 4   default         42332 non-null  bool
 5   housing         42332 non-null  bool
 6   loan            42332 non-null  bool
 7   contact         42332 non-null  object
 8   duration        42332 non-null  int64
 9   campaign        42332 non-null  int64
 10  pdays           1551 non-null   float64
 11  previous        42332 non-null  int64
 12  poutcome        42332 non-null  object
 13  emp.var.rate    42332 non-null  float64
 14  cons.price.idx  42332 non-null  float64
 15  cons.conf.idx   42332 non-null  float64
 16  euribor3m       33218 non-null  float64
 17  nr.employed     42332 non-null  int64
 18  subscribed      42332 non-null  bool
 19  date            42332 non-null  object
 20  latitude        42332 non-null  float64
 21  longitude       42332 non-null  float64
 22  id_             42332 non-null  object
dtypes: bool(4), float64(7), int64(5), object(7)
memory usage: 6.6+ MB

In [666]:
bank_df.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,subscribed,date,latitude,longitude,id_
27602,33,management,MARRIED,university.degree,False,True,False,telephone,181,1,...,-1.8,92.843,-50.0,1.757,50991,True,13-05-2017,41.990,-85.241,ca7bdffe-e2e2-4df0-968f-be8268c437d7
41289,38,admin.,SINGLE,high.school,False,True,False,cellular,86,1,...,-0.1,93.200,-42.0,NaN,51958,False,18-04-2016,28.619,-71.242,b60ac4bb-a7be-4e01-abce-683f27ef9d20
34530,42,blue-collar,MARRIED,basic.4y,False,False,False,cellular,131,2,...,-1.8,92.893,-46.2,1.266,50991,False,06-04-2018,28.347,-89.354,94271681-3db7-45cd-8447-1572ae75a215
13368,53,services,DIVORCED,basic.4y,True,True,False,cellular,89,1,...,1.4,93.918,-42.7,NaN,52281,False,17-02-2019,35.716,-75.840,91777770-80a1-4cf9-91c2-36e352cde370
41821,53,blue-collar,MARRIED,basic.4y,False,False,False,cellular,165,2,...,1.4,93.444,-36.1,4.967,52281,False,05-06-2019,35.599,-76.605,9fe0f8fc-47f1-433d-96cb-cd3e28f74dbb
39444,52,technician,MARRIED,university.degree,False,False,False,cellular,211,1,...,-1.8,93.876,-40.0,0.677,50087,True,18-10-2019,33.166,-84.308,bfb40cab-5248-4415-9424-317b05857dd6
22168,45,services,MARRIED,high.school,False,True,False,cellular,660,1,...,1.4,93.444,-36.1,4.963,52281,False,25-07-2015,46.374,-106.322,0212c133-93ee-46e5-abba-3341e5eb501e
28125,27,admin.,SINGLE,university.degree,False,True,True,cellular,98,1,...,-1.8,93.075,-47.1,1.445,50991,False,05-04-2018,47.504,-80.494,a09db40d-4c53-41ad-a66b-7b23d4a34a9c
31286,39,technician,DIVORCED,professional.course,False,True,False,telephone,175,1,...,-1.8,92.893,-46.2,1.334,50991,False,27-06-2018,33.729,-94.296,b171d0ac-4d35-49b0-b0ad-599a22d0e9b3
7163,41,blue-collar,MARRIED,basic.4y,True,True,False,telephone,151,2,...,1.1,93.994,-36.4,4.860,51910,False,28-10-2015,29.182,-79.797,a6fdaae2-3aea-49da-9cc2-b6beefd4b1b4
20897,34,technician,SINGLE,university.degree,False,False,False,telephone,214,2,...,1.4,93.444,-36.1,4.964,52281,False,18-05-2018,28.445,-104.306,e4764b97-f24c-419b-a8a9-cf09359d1018
25893,42,technician,MARRIED,basic.9y,False,False,False,cellular,294,2,...,-0.1,93.200,-42.0,4.120,51958,False,28-10-2016,46.868,-117.890,08e88044-1319-4168-a9c4-c4445b2ef152
752,52,blue-collar,SINGLE,high.school,True,True,True,telephone,124,1,...,1.1,93.994,-36.4,4.856,51910,False,12-12-2015,37.880,-109.772,c6df1f65-7889-4eb0-8ffe-296188e33ba3
8713,33,self-employed,MARRIED,university.degree,False,True,False,telephone,271,1,...,1.4,94.465,-41.8,4.866,52281,False,04-03-2018,41.897,-111.533,2cc47385-b519-492c-ad91-b2ed30b32311
17287,43,management,MARRIED,university.degree,True,False,True,cellular,219,2,...,1.4,93.918,-42.7,4.962,52281,False,25-01-2015,31.687,-106.280,5a964398-e29f-4f8b-820b-65cf7e9bb744

Exporamos los siguientes 3 data frames

In [667]:
customer_df_2012.head(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [668]:
customer_df_2013.head(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c
3,3,113859,1,1,2013-01-06,12,f8aaf334-949d-4943-a214-b64fe9c088b4
4,4,147317,0,0,2013-07-10,14,885fe85a-3718-4760-a32a-a57628cf7528

In [669]:
customer_df_2014.tail(10)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
14080,14080,159144,1,0,2014-10-14,1,0490dbb9-e21d-4b59-a402-93756e8f17da
14081,14081,51496,0,0,2014-09-18,12,d9f2c31c-7623-44df-9240-b4514bf21abd
14082,14082,68672,0,2,2014-03-08,22,4eed05de-2a98-4227-b488-32122009b638
14083,14083,73578,0,2,2014-03-11,26,0f0aca88-4088-4fe2-905f-44fb675d9493
14084,14084,9816,2,2,2014-09-18,31,cadadd4b-7ee5-4019-b13a-ca01bb67ca5b
14085,14085,156980,1,2,2014-05-17,7,5f432048-d515-4bb5-9c94-62db451f88d4
14086,14086,139820,0,0,2014-09-29,1,993bbbd6-4dbc-4a40-a408-f91f8462bee6
14087,14087,78470,2,2,2014-10-28,12,d6271666-319d-42c8-a741-cb22bf2c2093
14088,14088,144218,0,1,2014-07-01,9,f67fbfa8-6573-414d-a805-b26a2f1b1ceb
14089,14089,115155,0,2,2014-12-25,7,9727bc06-c11a-461a-a5bb-3d210467cc2a

Combinamos los 3 DF anteriores ya que tienes una estructura similar y coherente

In [670]:
df_customer_combinados = pd.concat([customer_df_2012, customer_df_2013, customer_df_2014], ignore_index=True)
df_customer_combinados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

In [671]:
df_customer_combinados.describe().round(2)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth
count,43170.00,43170.00,43170.00,43170.00,43170,43170.00
mean,7916.02,93227.39,1.00,1.00,2013-05-11 22:09:47.407922176,16.59
min,0.00,5841.00,0.00,0.00,2012-01-01 00:00:00,1.00
25%,3597.00,49608.00,0.00,0.00,2012-07-16 00:00:00,9.00
50%,7194.50,93009.50,1.00,1.00,2013-03-01 00:00:00,17.00
75%,11705.75,136740.50,2.00,2.00,2014-03-28 00:00:00,25.00
max,20114.00,180802.00,2.00,2.00,2014-12-31 00:00:00,32.00
std,5228.25,50498.18,0.82,0.82,NaN,9.24

In [672]:
# Ver cantidad de valores faltantes por columna en el DataFrame combinado
missing_values_customer = df_customer_combinados.isnull().sum()
missing_values_customer

Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

In [673]:
porcentaje_nulos_customer = df_customer_combinados.isnull().mean().round(4) * 100   
porcentaje_nulos_customer

Unnamed: 0           0.0
Income               0.0
Kidhome              0.0
Teenhome             0.0
Dt_Customer          0.0
NumWebVisitsMonth    0.0
ID                   0.0
dtype: float64

In [674]:
# registros que esten en df_customer_combinados pero no en bank_df
df_customer_combinados[~df_customer_combinados['ID'].isin(bank_df['id_'])].sample(25)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
17421,17421,157727,2,2,2012-07-09,10,4730acb0-00d8-4a8d-806c-098bb6780692
32999,3919,146347,0,1,2014-10-28,15,44e1ce4c-1e76-4730-9be7-cb808e68cac1
38550,9470,77349,1,0,2014-11-09,4,fdba0708-0b85-4d1c-8089-90274a3ace41
452,452,49950,0,1,2012-05-25,14,c8c695ba-e534-4581-b122-872b06a7d509
33696,4616,153218,2,0,2014-08-08,20,5e7f91e1-3996-4afe-a43f-03f4897938dc
4879,4879,160291,0,0,2012-05-21,1,318a6868-3744-4468-81ce-b24baebf9b62
19302,19302,154389,1,1,2012-05-07,10,3d38a1bb-2741-48d0-b717-a9034bad0444
2765,2765,23785,0,2,2012-10-23,6,c2d1ec1d-24ab-48cc-b2bd-39a65b1d9a66
24002,3887,29311,2,2,2013-02-11,27,dff31281-fcac-4019-94a1-3430f8128b87
24008,3893,70197,2,0,2013-08-24,4,a3e49010-bf26-40dc-a5ff-46a915c87625
23817,3702,92271,1,2,2013-06-27,10,b5db41ba-89d0-4dda-b5d2-6664464cbf9e
448,448,41447,2,0,2012-07-01,2,d06b92b4-6895-4afd-9549-21ab600b8a4e
17325,17325,132749,0,1,2012-10-29,19,f2b9d87d-4d0a-4675-af58-051f2848c1bc
16634,16634,97002,2,2,2012-12-17,24,c3c51e25-bca6-435b-8945-de42a5e55bae
24011,3896,12527,1,2,2013-12-27,29,44e31d7d-900e-467e-a607-078b065f4689
10337,10337,163773,0,2,2012-03-12,12,c3b843e5-133e-4f04-956d-e90d6e546e29
39777,10697,38267,2,0,2014-04-23,21,2a6e3730-e3a7-4d64-9bf2-ed8336560d4c
21013,898,73201,2,2,2013-02-20,15,f884060d-c631-471a-9c0b-722a5361c760
314,314,85356,0,1,2012-12-10,26,6d269bd3-8512-43d5-80fd-a4cd68299340
40520,11440,66249,2,0,2014-09-13,27,29333c19-6eb1-401d-9109-11975bde1143
674,674,96458,0,0,2012-05-16,26,ec518f61-19e6-41b8-990b-ed0e33b6937b
37999,8919,78332,0,2,2014-04-01,5,5a3eb192-36c2-4467-b11e-a0e1ef8229cc
316,316,71168,0,2,2012-02-26,1,3ecea40a-02ff-4bba-a29f-4b59f6b1aefd
34180,5100,92493,2,1,2014-12-11,10,0d88f7db-9133-4458-92ad-8f5a96d51c3e
8906,8906,90192,0,2,2012-08-30,23,a5f65498-6df1-4506-9c6c-9bcde8a5037f

Formateamos la columna "Dt_Customer" a fecha con formato

In [675]:
df_customer_combinados['Dt_Customer'] = df_customer_combinados['Dt_Customer'].dt.date

In [676]:
df_customer_combinados['Dt_Customer'] = pd.to_datetime(df_customer_combinados['Dt_Customer'], format='%d-%m-%Y')
df_customer_combinados['Dt_Customer'] = df_customer_combinados['Dt_Customer'].dt.strftime('%d-%m-%Y')

In [677]:
df_customer_combinados.head(5)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,04-04-2012,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,30-12-2012,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,02-02-2012,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,121393,1,2,21-12-2012,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,63164,1,2,20-06-2012,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [678]:
df_customer_combinados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  object
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: int64(5), object(2)
memory usage: 2.3+ MB

Combinamos los data frame de banco y cliente y lo llamamos "df_bank_cust"

In [679]:

# Realiza el merge para obtener solo las entradas que tienen coincidencia en ambos DataFrames
df_bank_cust = pd.merge(
    bank_df, 
    df_customer_combinados, 
    left_on='id_', 
    right_on='ID', 
    how='inner'  # Esta opción conserva solo las coincidencias
)

# Resultado
print(f"Número de coincidencias encontradas: {bank_cust_df.shape[0]}")

Número de coincidencias encontradas: 41320

In [680]:
df_bank_cust.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,latitude,longitude,id_,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
16112,46,services,MARRIED,high.school,False,True,True,telephone,36,1,...,24.913,-78.679,0ecdc97a-9da5-40e5-b428-1ec37eea4463,16472,27283,0,0,16-12-2012,26,0ecdc97a-9da5-40e5-b428-1ec37eea4463
24287,56,self-employed,DIVORCED,high.school,False,False,False,cellular,79,1,...,48.513,-114.901,577d9127-f22b-4363-a272-410d63b91f74,4713,165055,0,0,05-08-2013,31,577d9127-f22b-4363-a272-410d63b91f74
41355,26,admin.,SINGLE,university.degree,False,False,False,telephone,394,1,...,48.060,-74.498,6006c70e-7ba8-4218-a0af-86986a4d3801,13092,148740,2,1,24-07-2014,25,6006c70e-7ba8-4218-a0af-86986a4d3801
15263,42,housemaid,DIVORCED,basic.9y,True,False,False,cellular,272,2,...,41.288,-107.546,e889d73b-48fe-4c6f-8bff-c3273775ccd5,15617,85170,0,1,17-09-2012,26,e889d73b-48fe-4c6f-8bff-c3273775ccd5
11795,65,retired,MARRIED,basic.4y,True,True,False,telephone,50,1,...,33.651,-68.489,3a1c6571-af72-421d-9d7f-e47b5f30d3b7,12118,92746,1,1,10-04-2012,25,3a1c6571-af72-421d-9d7f-e47b5f30d3b7
11512,47,entrepreneur,SINGLE,university.degree,True,True,False,telephone,39,3,...,24.502,-105.320,694cb1f4-483c-4e31-8af5-6697ea1a5807,11829,67112,2,1,17-08-2012,21,694cb1f4-483c-4e31-8af5-6697ea1a5807
38790,40,student,SINGLE,unknown,False,False,False,cellular,342,2,...,43.778,-82.832,8d907221-d06a-44ff-8811-d09e173587c9,10480,85252,2,2,04-06-2014,3,8d907221-d06a-44ff-8811-d09e173587c9
15989,40,blue-collar,MARRIED,unknown,True,False,False,cellular,1608,13,...,44.270,-95.572,bab465e6-60b9-4f9f-bfd5-47df82783c38,16349,39851,1,0,17-01-2012,18,bab465e6-60b9-4f9f-bfd5-47df82783c38
232,40,services,MARRIED,unknown,False,False,False,telephone,408,2,...,41.015,-67.337,46c8d84e-2d68-4438-a4fa-30fc8f3c887c,254,34613,0,2,18-05-2012,4,46c8d84e-2d68-4438-a4fa-30fc8f3c887c
41540,38,admin.,DIVORCED,high.school,False,False,False,telephone,81,1,...,42.374,-74.327,dbef17db-a5fd-49f5-abec-7669d0447795,13278,30764,1,2,15-09-2014,12,dbef17db-a5fd-49f5-abec-7669d0447795
33621,43,blue-collar,MARRIED,basic.4y,False,False,True,cellular,722,2,...,29.847,-78.665,c182cf6d-f386-4e65-8b36-a0d3998f7948,5195,133973,1,1,04-02-2014,17,c182cf6d-f386-4e65-8b36-a0d3998f7948
24964,44,entrepreneur,MARRIED,high.school,False,False,False,cellular,130,1,...,28.449,-99.366,14db7232-6f81-43c5-8d2b-a88e610b0074,5392,168617,2,2,15-03-2013,11,14db7232-6f81-43c5-8d2b-a88e610b0074
5873,38,admin.,DIVORCED,high.school,True,False,False,telephone,161,2,...,32.508,-88.972,d0636e39-9ecc-4318-a509-76c92f0dba6c,6086,58645,1,0,27-03-2012,5,d0636e39-9ecc-4318-a509-76c92f0dba6c
19225,32,admin.,MARRIED,high.school,False,True,False,cellular,117,1,...,37.099,-79.508,45674f36-a001-4140-abb9-166435426a95,19665,35579,0,0,22-11-2012,10,45674f36-a001-4140-abb9-166435426a95
6044,34,blue-collar,MARRIED,basic.9y,False,True,False,telephone,355,2,...,43.508,-78.933,ef08ede8-ae03-49bf-9655-d59d519fb7cb,6263,40839,0,1,14-10-2012,6,ef08ede8-ae03-49bf-9655-d59d519fb7cb

Quitamos la columna id_ ya que el valor es el mismo que en la columna ID

In [681]:
df_bank_cust = df_bank_cust.drop(columns=['id_'])
df_bank_cust.sample(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,date,latitude,longitude,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
24230,35,blue-collar,MARRIED,professional.course,False,True,False,cellular,114,2,...,08-10-2019,37.819,-115.492,4656,120493,0,0,15-12-2013,30,fdfdd687-9b11-4a24-aa40-02fed95101e4
15565,43,admin.,MARRIED,high.school,False,True,False,cellular,250,2,...,23-01-2018,26.925,-84.050,15919,75925,0,2,30-03-2012,21,6de7b71d-2586-44e7-b0bc-94dd339447ff
15202,28,technician,SINGLE,university.degree,False,False,False,cellular,453,3,...,19-02-2018,42.061,-83.892,15556,163310,1,2,13-02-2012,11,f659d8a4-cd66-46a8-aea5-0cc90bd9e86f
1158,60,entrepreneur,MARRIED,basic.4y,False,True,False,telephone,82,1,...,09-02-2017,45.206,-116.530,1289,20617,1,2,02-04-2012,19,70d0bc2b-cc86-43b5-939b-48993da102d9
10818,58,self-employed,DIVORCED,professional.course,False,False,False,telephone,197,1,...,22-03-2019,40.372,-92.250,11122,94896,2,2,09-07-2012,27,e6723c5f-d8e9-4b2f-b36c-91985183df7e
29871,42,management,SINGLE,university.degree,False,True,False,cellular,77,2,...,16-07-2019,30.622,-72.142,1404,154830,0,2,03-03-2014,18,81ee624e-bf60-4a51-a750-aecb5a989385
34112,37,technician,MARRIED,university.degree,False,True,True,cellular,172,2,...,27-09-2017,41.027,-79.016,5693,20489,0,1,04-07-2014,32,272dd75f-a9a4-40be-8262-c1e965da7929
7146,38,blue-collar,MARRIED,basic.9y,True,True,False,telephone,123,1,...,14-06-2017,38.882,-88.733,7383,39967,2,2,08-11-2012,1,cdd4f97f-0332-482f-9023-1b1579e48256
26247,39,technician,MARRIED,university.degree,False,False,True,cellular,418,2,...,03-04-2015,37.107,-104.177,6688,9951,2,0,07-03-2013,11,d59eef89-1b10-4042-aee0-502585fa1d2c
19419,30,admin.,DIVORCED,university.degree,False,True,True,cellular,316,1,...,05-06-2018,31.448,-84.476,19859,55203,0,2,24-07-2012,9,15ff8d64-e7e4-49a9-823f-a26a2114beff
28862,39,entrepreneur,MARRIED,university.degree,True,True,False,cellular,68,1,...,27-11-2017,46.540,-108.167,375,51308,2,2,19-12-2014,2,235e2d06-3079-4032-91bb-e8adf4f70374
17724,37,technician,SINGLE,university.degree,False,True,False,telephone,185,2,...,24-02-2017,32.596,-102.970,18127,154283,1,2,11-05-2012,29,74c893be-3b01-48b1-81b5-875ee1875acf
687,37,blue-collar,MARRIED,basic.4y,True,True,True,telephone,195,2,...,18-06-2018,39.904,-71.402,770,156010,1,0,30-04-2012,3,55f6c5a2-153a-45d3-89c9-ca832f8a9254
752,34,admin.,SINGLE,high.school,False,True,False,telephone,359,1,...,13-11-2016,27.200,-89.429,847,112959,1,1,13-08-2012,22,82044973-a169-4ca0-9411-83dce367d07d
19015,47,blue-collar,MARRIED,basic.4y,False,False,False,cellular,82,1,...,30-03-2017,41.814,-105.548,19454,172468,0,0,03-06-2012,32,68e6b2b8-27b7-4e6c-92ab-3ca7f83f2cb1

Reseteamos el indice

In [682]:

df_bank_cust = df_bank_cust.reset_index()
df_bank_cust = df_bank_cust.drop(columns=['index'])
df_bank_cust.head(15)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,...,date,latitude,longitude,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,49,housemaid,MARRIED,basic.4y,False,False,False,telephone,261,1,...,02-08-2019,41.495,-71.233,0,161770,1,0,04-04-2012,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57,services,MARRIED,high.school,True,False,False,telephone,149,1,...,14-09-2016,34.601,-83.923,1,85477,1,1,30-12-2012,7,e9d37224-cb6f-4942-98d7-46672963d097
2,37,services,MARRIED,high.school,False,True,False,telephone,226,1,...,15-02-2019,34.939,-94.847,2,147233,1,1,02-02-2012,5,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40,admin.,MARRIED,basic.6y,False,False,False,telephone,151,1,...,29-11-2015,49.041,-70.308,3,121393,1,2,21-12-2012,29,9991fafb-4447-451a-8be2-b0df6098d13e
4,56,services,MARRIED,high.school,False,False,True,telephone,307,1,...,29-01-2017,38.033,-104.463,4,63164,1,2,20-06-2012,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb
5,45,services,MARRIED,basic.9y,True,False,False,telephone,198,1,...,26-09-2015,24.689,-101.643,5,143854,0,1,24-01-2012,26,d63ede72-0b6d-45b1-8872-385ac6897f65
6,59,admin.,MARRIED,professional.course,False,False,False,telephone,139,1,...,25-01-2019,31.456,-94.561,6,76439,1,0,15-08-2012,3,5e3483e5-236d-437d-8351-541f9d09b9dd
7,40,blue-collar,MARRIED,unknown,True,False,False,telephone,217,1,...,25-09-2017,46.871,-122.235,7,159686,1,1,10-12-2012,21,87fdc08b-30ae-4dab-803f-561ecdf27ff0
8,24,technician,SINGLE,professional.course,False,True,False,telephone,380,1,...,18-01-2018,44.632,-85.811,8,179933,0,0,22-08-2012,18,87b79988-2be5-419d-88f4-56655852c565
9,25,services,SINGLE,high.school,False,True,False,telephone,50,1,...,02-11-2016,30.297,-117.382,9,77504,1,0,09-02-2012,18,ea6b7d04-9271-4c0a-a01f-07795d164aba
10,40,blue-collar,MARRIED,unknown,True,False,False,telephone,55,1,...,30-11-2015,43.616,-90.902,10,92882,1,1,05-01-2012,9,8d700df5-0c33-4517-8cf8-92e1c92c9c12
11,25,services,SINGLE,high.school,False,True,False,telephone,222,1,...,17-04-2016,49.118,-85.121,11,84813,0,1,06-06-2012,30,ca5c0d7a-8bbd-42b3-8351-1074c5be011a
12,29,blue-collar,SINGLE,high.school,False,False,True,telephone,137,1,...,14-06-2016,30.047,-112.472,12,102006,0,1,24-03-2012,18,66a752e2-b2f1-440c-9a8f-cc3b10d74dd0
13,57,housemaid,DIVORCED,basic.4y,False,True,False,telephone,293,1,...,25-08-2015,28.873,-70.852,13,140801,2,1,11-02-2012,32,54b1ea8a-a909-45d9-9562-775b64ac9c29
14,35,blue-collar,MARRIED,basic.6y,False,True,False,telephone,146,1,...,19-09-2016,36.188,-109.835,14,73262,2,2,10-09-2012,27,3a7b7570-aba9-40bc-9f80-3433d064b5b7

In [684]:
df_bank_cust.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42332 entries, 0 to 42331
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                42332 non-null  int64
 1   job                42332 non-null  object
 2   marital            42332 non-null  object
 3   education          42332 non-null  object
 4   default            42332 non-null  bool
 5   housing            42332 non-null  bool
 6   loan               42332 non-null  bool
 7   contact            42332 non-null  object
 8   duration           42332 non-null  int64
 9   campaign           42332 non-null  int64
 10  pdays              1551 non-null   float64
 11  previous           42332 non-null  int64
 12  poutcome           42332 non-null  object
 13  emp.var.rate       42332 non-null  float64
 14  cons.price.idx     42332 non-null  float64
 15  cons.conf.idx      42332 non-null  float64
 16  euribor3m          33218 non-null  float64
 17  nr.employed        42332 non-null  int64
 18  subscribed         42332 non-null  bool
 19  date               42332 non-null  object
 20  latitude           42332 non-null  float64
 21  longitude          42332 non-null  float64
 22  Unnamed: 0         42332 non-null  int64
 23  Income             42332 non-null  int64
 24  Kidhome            42332 non-null  int64
 25  Teenhome           42332 non-null  int64
 26  Dt_Customer        42332 non-null  object
 27  NumWebVisitsMonth  42332 non-null  int64
 28  ID                 42332 non-null  object
dtypes: bool(4), float64(7), int64(10), object(8)
memory usage: 8.2+ MB

In [ ]:
porcentaje_nulos_bank_cust = df_bank_cust.isnull().mean().round(4) * 100
print(porcentaje_nulos_bank_cust)

In [ ]:
bank_cust_df.sample(10)

In [ ]:
#tenenemos que selecionar solo las columnas numéricas antes de calcular la correlación
numeric_bank_df = bank_df.select_dtypes(include=['float', 'int']).columns

In [ ]:
# Estudiamos la correlacion de la columna 'euribor3m'
correlations_euribor = bank_df[numeric_bank_df].corr()['euribor3m'].drop('euribor3m')
print(correlations_euribor)

In [ ]:
# estudiamos la correlacione con la columna 'cons.price.idx'

correlations_cons_price = bank_df[numeric_bank_df].corr()['cons.price.idx'].drop('cons.price.idx')
print(correlations_euribor)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Seleccionar solo columnas numéricas
numeric_cols = bank_df.select_dtypes(include='number').columns

# Crear el mapa de calor
sns.heatmap(bank_df[numeric_cols].corr(), annot=False, cmap='coolwarm')
plt.title("Mapa de calor de correlaciones numéricas")
plt.show()